data:
  buffer_size: 2048
  sampling_rate: 48000
  inp_channels: 1
  out_channels: 1
  num_conds: 2
  norm_tensor: [[0, 4], [0, 4]]
  train_path: data/overdrive/boss_od3/train
  valid_path: data/overdrive/boss_od3/valid
  test_path: data/overdrive/boss_od3/test
model:
  arch: dynamichyper-gru
  main_rnn_hidden_size: 32
  layer_norm: False
  rnn_bias: True 
  hyper_rnn_size: 8 
  n_z_size: 8 
loss:
  loss_func: hybrid_loss
  pre_emp: True 
device: cuda
env:
  expdir: exp/boss_od3/dynamichyper_gru_32
  gpu: 0
  gpu_id: 0
  is_jit: False
  debug_mode: True
inference:
  batch_size: 1
train:
  batch_size: 80
  epochs: 100
  interval_log: 10
  interval_ckpt: 1500
  interval_val: 1500
  lr_patience: 2
  improvement_patience: 4 
  lr: 0.001