data:
  buffer_size: 2048
  sampling_rate: 44100
  inp_channels: 1
  out_channels: 1
  num_conds: 6
  norm_tensor: [[0, 1], [0, 1], [-1, 1], [-1, 1], [-1, 1], [-1, 1]]
  train_path: ../../../data/audio_test/
  valid_path: ../../../data/audio_test/
  test_path: ../../../data/audio_test/
model:
  arch: concat-tcn
  n_blocks: 8
  kernel_size: 4
  dilation_growth: 2
  n_channels: 8
  causal: True
loss:
  loss_func: hybrid_loss
  pre_emp: True 
device: cuda
env:
  expdir: exp/vocaloid/concat_tcn_16
  gpu: 0
  gpu_id: 0
  is_jit: False
  debug_mode: True
inference:
  batch_size: 1
train:
  batch_size: 80
  epochs: 10
  interval_log: 10
  interval_ckpt: 1500
  interval_val: 1500
  lr_patience: 2
  improvement_patience: 4 
  lr: 0.0005