data:
  buffer_size: 2048
  sampling_rate: 44100
  inp_channels: 1
  out_channels: 1
  train_x_path: ../../../data/audio/sv_teto_0_0_0_0_MixDown.wav
  train_y_path: ../../../data/audio/sv_teto_0_1_1_1_MixDown.wav
  valid_x_path: ../../../data/audio/sv_teto_0_0_0_0_MixDown.wav
  valid_y_path: ../../../data/audio/sv_teto_0_1_1_1_MixDown.wav
  test_x_path: ../../../data/audio/sv_teto_0_0_0_0_MixDown.wav
  test_y_path: ../../../data/audio/sv_teto_0_1_1_1_MixDown.wav
model:
  arch: snapshot-tcn
  n_blocks: 9
  kernel_size: 12
  dilation_growth: 2
  n_channels: 32
  causal: True
loss:
  loss_func: hybrid_loss
  pre_emp: True 
device: cuda
env:
  expdir: exp/vocaloid/snapshot_tcn
  gpu: 0
  gpu_id: 0
  is_jit: False
  debug_mode: True
inference:
  batch_size: 1
train:
  batch_size: 30
  epochs: 20
  interval_log: 10
  interval_ckpt: 1500
  interval_val: 1500
  lr_patience: 2
  improvement_patience: 4 
  lr: 0.0005