data:
  buffer_size: 16384
  sampling_rate: 44100
  inp_channels: 1
  out_channels: 1
  num_conds: 1
  norm_tensor: [[0, 100]]
  train_path: data/compressor/la2a_full_modeling/train
  valid_path: data/compressor/la2a_full_modeling/valid
  test_path: data/compressor/la2a_full_modeling/test
model:
  arch: film-gcn
  n_blocks: 9
  kernel_size: 3
  dilation_growth: 2
  n_channels: 16
  causal: True 
  pre_film_size: 16
  pre_film_blocks: 3 
loss:
  loss_func: hybrid_loss
  pre_emp: True 
device: cuda
env:
  expdir: exp/compressor/film_gcn_trans
  gpu: 0
  gpu_id: 0
  is_jit: False
  debug_mode: True
inference:
  batch_size: 1
train:
  batch_size: 80
  epochs: 200
  interval_log: 10
  interval_ckpt: 1500
  interval_val: 1500
  lr_patience: 2
  improvement_patience: 6
  lr: 0.001