data:
  buffer_size: 8192
  sampling_rate: 44100
  inp_channels: 1
  out_channels: 1
  train_x_path: ./data/snapshot_modeling_example/train/train_x.wav
  train_y_path: ./data/snapshot_modeling_example/train/train_y.wav
  valid_x_path: ./data/snapshot_modeling_example/valid/valid_x.wav
  valid_y_path: ./data/snapshot_modeling_example/valid/valid_y.wav
  test_x_path: ./data/snapshot_modeling_example/test/test_x.wav
  test_y_path: ./data/snapshot_modeling_example/test/test_y.wav
model:
  arch: snapshot-gcn
  n_blocks: 9
  kernel_size: 3
  dilation_growth: 2
  n_channels: 16
  causal: True 
loss:
  loss_func: 'hybrid_loss' 
  pre_emp: True 
device: cuda
env:
  expdir: exp/snapshot_example
  gpu: 0
  gpu_id: 0
  is_jit: False
  debug_mode: True
inference:
  batch_size: 1
train:
  batch_size: 25
  epochs: 20
  interval_log: 10
  interval_ckpt: 50
  interval_val: 50
  lr_patience: 2
  improvement_patience: 6
  lr: 0.001