data:
  buffer_size: 2048
  sampling_rate: 48000
  inp_channels: 1
  out_channels: 1
  train_x_path: /home/yytung/projects/pyneuralfx/frame_work/data/overdrive/boss_od3/train/x/x_d0_t0.wav
  train_y_path: /home/yytung/projects/pyneuralfx/frame_work/data/overdrive/boss_od3/train/y/y_d0_t0.wav
  valid_x_path: /home/yytung/projects/pyneuralfx/frame_work/data/overdrive/boss_od3/train/x/x_d0_t0.wav
  valid_y_path: /home/yytung/projects/pyneuralfx/frame_work/data/overdrive/boss_od3/train/y/y_d0_t0.wav
  test_x_path: /home/yytung/projects/pyneuralfx/frame_work/data/overdrive/boss_od3/train/x/x_d0_t0.wav
  test_y_path: /home/yytung/projects/pyneuralfx/frame_work/data/overdrive/boss_od3/train/y/y_d0_t0.wav
model: 
  arch: snapshot-lstm
  main_rnn_hidden_size: 16
  layer_norm: False
  rnn_bias: True 
loss:
  loss_func: hybrid_loss
  pre_emp: True 
device: cuda
env:
  expdir: exp/boss_od3/snapshot_vanilla_rnn
  gpu: 0
  gpu_id: 0
  is_jit: False
  debug_mode: True
inference:
  batch_size: 1
train:
  batch_size: 80
  epochs: 1
  interval_log: 10
  interval_ckpt: 1500
  interval_val: 1500
  lr_patience: 2
  improvement_patience: 4 
  lr: 0.001